version: "3.10"

services:
  bot:
    build: .
    container_name: air-bot
    environment:
      - DEBUG=True
    volumes:
      - bot_logs:/app/logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: air-mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27016:27017"

volumes:
  bot_logs:
  mongodb_data:
  mongodb_config:
